apiVersion: apps/v1
kind: Deployment
metadata:
name: django-messaging-blue
spec:
replicas: 1
selector:
matchLabels:
app: django-messaging-blue
template:
metadata:
labels:
app: django-messaging-blue
spec:
containers:
- name: django-container
image: your-docker-username/django-messaging-app:latest
ports:
- containerPort: 8000
command: ["python"]
args: ["manage.py", "runserver", "0.0.0.0:8000"]